# Generated by Django 5.0.4 on 2024-05-17 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom_class_name_classroom_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='room_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='forum',
            name='type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 10, 38, 33, 725723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 10, 38, 33, 725723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 10, 38, 33, 725723, tzinfo=datetime.timezone.utc)),
        ),
    ]
