# Generated by Django 5.0.4 on 2024-05-22 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 18, 54, 585171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 18, 54, 585171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 14, 18, 54, 585171, tzinfo=datetime.timezone.utc)),
        ),
    ]
